### ISSUE TITLE
Activation Failure in Version 0.3

### ISSUE THREAD

**Issue by lurenpluto** [buckyos/buckyos#25]
### Description:
After installing version 0.3 on my OOD server and forwarding port 3180 to local via SSH, I attempted to activate the service by opening `http://localhost:3180/index.html` in my browser. However, an error occurred during the final confirmation step before activation. 

### Steps to Reproduce:
1. Install version 0.3
2. Forward port 3180 to local via SSH
3. Open http://localhost:3180/index.html in a browser to active service
4. Proceed to the final confirmation step before activation

### Expected Behavior:
The service should be activated successfully.

### Actual Behavior:
An error occurred during the final confirmation step before activation. The browser console displays the following error message:

```
POST http://localhost:3180/kapi/active 500 (Internal Server Error)
_call @ buckyos.mjs:39
call @ buckyos.mjs:28
active_ood @ active_lib.ts:134
do_active @ active_lib.ts:190
await in do_active
do_active @ final_check_dlg.ts:13
(anonymous) @ final_check_dlg.ts:31

final_check_dlg.ts:40 Activation failed RPCError: RPC call error: 500
    at kRPCClient._call (buckyos.mjs:47:15)
    at async active_ood (active_lib.ts:134:18)
    at async do_active (active_lib.ts:190:29)
    at async FinalCheckDlg.do_active (final_check_dlg.ts:13:16)
```

### Additional Information:
The OOD service log in /opt/buckyos/logs/node_daemon.log received the request but encountered an error while processing it:

```
2024-11-11 13:50:26.507 [INFO] |==>recv kRPC req: {"method":"do_active","params":{"user_name":"xman","zone_name":"xman.web3.buckyos.io","gateway_type":"BuckyForward", ...
2024-11-11 13:50:26.910 [ERROR] Error handling request: Failed due to reason: Failed to register device to sn: Failed due to reason: rpc call error: 500 Internal Server Error
```

I believe this error led to the activation failure on the web end.

After the issue occurred, I tried restarting the ood_daemon service, but the same error persisted. Additionally, the logs from the previous process were overwritten after the restart, which may have resulted in the loss of diagnostic information. I suggest appending the date and process ID to the logs to prevent them from being overwritten after a restart.

**Comment by waterflier** [comment]
I was trying to track a HTTPs stuck bug with a debugger yesterday (and it just kept running). Then the power went out and my terminal crashed, and the whole sn_server crashed.

The last line of the server log was:

```
11-13 11:30:02.850 [INFO] 75.4.200.194:37782==> rtcp package, len:175
11-13 11:30:02.850 [ERROR] read first package error:parse package error
```

So, at 11-13 11:30:02.850 UTC my house lost power! (FUCK PG&E again!)

Now sn_server has been restarted in deamon mode, please try again ~
